# Generated by Django 2.0 on 2017-12-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedAttrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionIds', models.IntegerField()),
                ('minTripStartDate', models.DateField()),
                ('maxTripStartDate', models.DateField()),
                ('lengthOfStay', models.IntegerField()),
                ('maxStarRating', models.IntegerField()),
                ('minStarRating', models.IntegerField()),
                ('maxTotalRate', models.IntegerField()),
                ('minTotalRate', models.IntegerField()),
                ('maxGuestRating', models.IntegerField()),
                ('minGuestRating', models.IntegerField()),
            ],
        ),
    ]
